server:
  port: 9979
spring:
  application:
    ##项目名称可以修改
    name: delivery
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/takeout?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1111
  servlet:
    multipart:
      enabled: true #允许上传文件
      max-file-size: 3MB #允许上传文件的大小，默认1MB
      max-request-size: 3MB #允许上传最大文件大小，默认1MB
mybatis-plus:
  configuration:
    ##在映射项目实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    ##例如数据库中的id_number映射为Employee类中的属性idNumber??
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\img\

tokenKey: fatTsai9979

weixin:
  appid: xxxx
  secret: xxxx
  getPhoneNumberUrl: https://api.weixin.qq.com/wxa/business/getuserphonenumber?access_token=
  getAccessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
